# Generated by Django 5.1.3 on 2024-12-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogband', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
